const taskerTypes = Object.freeze({
  DRAWER_OPEN: 'DRAWER_OPEN',
  DRAWER_CLOSE: 'DRAWER_CLOSE',
  TOGGLE_DRAWER: 'TOGGLE_DRAWER',
  MODAL_OPEN: 'MODAL_OPEN',
  MODAL_CLOSE: 'MODAL_CLOSE',
  SET_REFRESH: 'SET_REFRESH',
  SET_COLECTIONS: 'SET_COLECTIONS',
  EDIT_MODAL_FORM: 'EDIT_MODAL_FORM',
  CLEAN_EDIT_MODAL_FORM: 'CLEAN_EDIT_MODAL_FORM',
  SET_TASKS: 'SET_TASKS',
  SET_REFRESH_COLECTION: 'SET_REFRESH_COLECTION',
  OPEN_CALENDAR_MODAL: 'OPEN_CALENDAR_MODAL',
  CLOSE_CALENDAR_MODAL: 'CLOSE_CALENDAR_MODAL',
  SET_REFRESH_CALENDAR: 'SET_REFRESH_CALENDAR',
  CLEAN_CONTEXT: 'CLEAN_CONTEXT',
});

export default taskerTypes;
